name: Pull Request Deployment to Sandpit Workspace	        
        
on:	              
  push:	             
  #pull_request:	           
  #  types:	           
  #    - opened	       
  #  branches:	              
  #  - sandpit-workflow	        
              
permissions:	               
  id-token: write	            
  contents: read	         	        
        
jobs:	              
  create-db-config-sandpit:	              
    runs-on: self-hosted	              
    environment: sandpit	             
    env:	              
      DB_USERNAME: ${{ secrets.DB_USERNAME }}	             
      DB_PASS: ${{ secrets.DB_PASS }}	        
        
    steps:	        
      - name: Checkout
        uses: actions/checkout@v3	       
      - name: Install Dependencies	         
        run: |	          
             sudo yum -y install postgresql-client            
      - name: Database Login	        
        
        run: |	        
        
          psql "host=aurora-postgresql-dni-stage.cluster-coekcbwbqb9h.eu-west-1.rds.amazonaws.com port=5432 sslmode=verify-full sslrootcert=full_path_to_ssl_certificate password=$RDSPASSWORD dbname=dni_ingestion_framework_sandpit user=ifw_deployment_user"	        
        

        
        
      #- name: Database Login	        
        
      #  run: |	        
        
      #    psql -h aurora-postgresql-dni-stage.cluster-coekcbwbqb9h.eu-west-1.rds.amazonaws.com -p 5432 -d dni_ingestion_framework_sandpit -U ifw_deployment_user	        
        

        
        
#authenicate to db	        
        
#deploy Database objects creation scripts	        
        
#deploy metadata scripts
